type Query {
  search(product: String, guide: String): SearchResult
}

type SearchResult {
  products: [String]
  guides: [String]
  results: [Article]
}

type Article {
  id: ID
  title: String
  summary: String
}
